### ISSUE TITLE
Allow Little-Endian byte order

### ISSUE THREAD

**Issue by gelupa** [FIXTradingCommunity/fix-simple-open-framing-header#2]
On most platforms we use little endian instead of big endian.  To convert the Message_Length  field in the SOFH is easy, a single ntohl() call will suffice.  And the x86-32 and x86-64 platforms have a 32-bit 'bswap' assembly instruction, the reversion can be done within a few instructions inline:
uint32_t asm_ntohl(uint32_t a)
{
   __asm
    {
       mov eax, a;
       bswap eax; 
    }
}

So it will not incur much performance penalties in practice. But this discovery will give us  another interesting question: given the high performance in doing so, why do we strive to use the native byte order in SBE whenever possible?  It is recommended to clarify the main difference here, that is , for SOFH, only one such conversion is needed and for the transmitted messages, you may have to do multiple conversions in one message.

**Comment by da4089** [comment]
Internet tradition (eg. IP and TCP) was to use big endian binary integers.
With the dominance of IA32 and then AMD64 instruction sets, little endian has become common.

The options are to:
(a) always use big-endian
(b) always use little-endian
(c) use a "receiver makes right" scheme, with an explicit flag in the header
(d) use a "receiver makes right" scheme, with an implicit flag in the header (ie. byte order of known magic value)
(e) use a negotiation scheme to agree on the encoding for a session

Older protocols typically use (a), newer designs tend towards (b), (c) comes from things like CORBA's CDR, (d) saves a bit if you don't have a flag word, and the 16 bits of _Encoding_Type_ could probably afford the loss; (e) is a level of complexity that FIX has so far avoided.

In 2019, (b) is likely the most efficient, likely followed by (c) or (a).  Given the total cost of handling SOFH, a byte-swap is not insignificant, although relative to the cost of processing the entire message/packet, it's likely immaterial.

**Comment by gelupa** [comment]
I tried the bswap assembly mentioned above in linux using gcc and compared it with ntohl(). 
Homemade assembly solution runs slower than the ntohl(). By using ntohl(), 10,000,000 loops will cost 5,402,353 nano-seconds(0.5ns for a ntohl), the homemade solution will cost 8,326,314 nano-seconds(0.8ns for a bswap). So a big-endian to little-endian conversion will add approximately 0.5ns in latency. Whether it is acceptable is dependent on our target, of course.
 
Below is the relevant code fragment of my testing. I introduced a sum to prevent the compiler from optimizing away the long loop.

uint32_t  sum = 0;
for(uint32_t i = 0; i < LOOP_COUNT; i++)
{
     uint32_t v = 0;
     asm("movl %1, %%eax; bswap %%eax; movl %%eax, %0;"
         :"=r"(v)
         :"r"(i)
         :"%eax"
         );
     sum += v;
}

and 

uint32_t  sum = 0;
for(uint32_t i = 0; i < LOOP_COUNT; i++)
{
     uint32_t v = ntohl(i);
     sum += v;
}

**Comment by gelupa** [comment]
I will vote for option (b), always use little-endian

**Comment by kleihan** [comment]
The question had been raised back in Sep 2014 when RC1 was published for review (see https://forum.fixtrading.org/t/public-comment-period-fix-simple-open-framing-header-release-candidate-1/158/4). My answer at the time had been:

> There was no strong argument one way or the other. Byte swapping was not seen as a real obstacle for those that need little-endian instead of big-endian. Additionally, the framing header is optional and minimal in size. Making the byte order configurable for the framing header does not give an advantage as it requires extra processing. SBE works without a framing header and supports both byte orders (configurable via meta-data, little-endian as default).

The choice against SOFH configurability on the level of each message was intentional. I would propose an option (f) in addition to (a)-(e) above, i.e. agree byte order out of band (by whatever means, e.g. negotiation, meta-data, session config) and assume big endian (and use byte swapping if needed) if no such information is available to the decoder. I do not see an issue of bilaterally agreeing little endian. We may have to update the spec for that but it does not impact existing applications. 

Introducing any change to the wire format would however require to define a Version 2.0 for SOFH.
